# frozen_string_literal: true

# The server side of collaborative documents: one channel speaking the
# y-websocket protocol (document sync plus presence). Generated by
# `rails generate yrby:install`; the store calls are yours to point anywhere.
class DocumentChannel < ApplicationCable::Channel
  include Y::ActionCable::Sync

  # Rebuild a document from durable storage (nil means a brand-new doc).
  on_load { |key| YrbyDocumentStore.load(key) }

  # Record each CRDT delta durably. Runs before the change is acknowledged
  # or broadcast; raising rejects the change and the client retransmits.
  on_change { |key, update| YrbyDocumentStore.append(key, update) }

  def subscribed = sync_subscribed(params[:id])
  def receive(data) = sync_receive(data, params[:id])
end
