# frozen_string_literal: true

# The server side of collaborative documents: one channel speaking the
# y-websocket protocol (document sync plus presence). Generated by
# `rails generate yrby:install`; the store calls are yours to point anywhere.
class DocumentChannel < ApplicationCable::Channel
  include Y::ActionCable::Sync

  # Rebuild a document from durable storage (nil means a brand-new doc).
  on_load { |key| <%= model_class_name %>.load(key) }

  # Record each CRDT delta durably. Runs before the change is acknowledged
  # or broadcast; raising rejects the change and the client retransmits.
  on_change { |key, update| <%= model_class_name %>.append(key, update) }

  def subscribed
    return reject unless authorized?(params[:id])

    sync_subscribed(params[:id])
  end

  def receive(data) = sync_receive(data, params[:id])

  private

  # Fails closed: no one collaborates on a document until this says so.
  # Wire it to your app's auth — e.g. identify current_user on the cable
  # connection, then check it may read AND write this document (a raising
  # on_change only covers transient store failures, not access control).
  def authorized?(_document_key)
    false
  end
end
